version: "3.7"

services:
  duck_hack:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: duck_hack_cloud
    environment:
      DB_URL: sqlite:///data/reflex.db
    restart: always
    volumes:
       - db-data:/app/data
       - upload-data:/app/uploaded_files
    ports:
      - 82:3000
      - 83:8000
    networks:
      - npm
      - duck_hack_cloud

networks:
  duck_hack_cloud:
    name: duck_hack_cloud
    driver: bridge
  npm:
    external: true

volumes:
  # SQLite data
  db-data:
  # Uploaded files
  upload-data: